name: Publish Mod

# Set the workflow manual for now
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install jq (if not already available)
      - name: Install jq
        run: sudo apt-get install -y jq

      # Read the manifest.json to get data from the manifest
      - name: Read manifest.json
        id: manifest
        run: |
          MODPACK_NAME=$(jq -r '.name' src/manifest.json)
          VERSION=$(jq -r '.version_number' src/manifest.json)
          DESCRIPTION=$(jq -r '.description' src/manifest.json)
          echo "modpack_name=$MODPACK_NAME" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "description=$DESCRIPTION" >> $GITHUB_ENV

      # Zip the required files
      - name: Zip files
        run: |
          cd src  # Change to the src directory
          zip -r "../${{ env.modpack_name }}-${{ env.version }}.zip" *

      # Debug: List the contents of the zip file, debug env variables
      - name: List Zip Contents
        run: |
          echo "modpack_name: ${{ env.modpack_name }}"
          echo "version: ${{ env.version }}"
          echo "description: ${{ env.description }}"
          unzip -l "${{ env.modpack_name }}-${{ env.version }}.zip"

      # Upload to Thunderstore
      - name: Upload to Thunderstore (if enabled)
        # if: ${{ secrets.THUNDERSTORE_ENABLED == 'true' }}
        uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          file: "${{ env.modpack_name }}-${{ env.version }}.zip"
          namespace: Jumpperi                       # Your Team in Thunderstore
          description: ${{ env.description }}       # The description of the package
          token: ${{ secrets.THUNDERSTORE_TOKEN }}  # Your Thunderstore API token
          name: ${{ env.modpack_name }}             # the name of the package
          version: ${{ env.version }}               # The version of the package
          community: valheim                        # community in Thunderstore to publish to
          repo: valheim.thunderstore.io             # the URL or repository to publish to
          categories: |                             # the categories of the package. Use slug names, get them from thunderstore API, example: curl -X GET "https://thunderstore.io/api/experimental/community/valheim/category/" -H  "accept: application/json" | jq
            modpacks